name: ci
on:
  push:
    braches: 
      - master

jobs:
  firebase:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14.4.0

      - name: Install dependencies
        run: |
          yarn
      - name: Build nuxt app
        # env:  
        #   API_KEY: ${{ secrets.API_KEY }}
        #   AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        #   PROJECT_ID: ${{ secrets.PROJECT_ID }}
        #   STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        #   MESSAGE_SENDER_ID: ${{ secrets.MESSAGE_SENDER_ID }}
        #   APP_ID: ${{ secrets.APP_ID }}
        #   MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }} 
        run: |
          yarn install && yarn build
      - name: Setup Firebase CLI
        run: |
          npm install -g firebase-tools
      - name: Deploy Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}  
        run: |
          firebase deploy --token $FIREBASE_TOKEN
